# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0002_remove_user_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('planner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='buddies.User')),
                ('user_solo', models.ManyToManyField(null=True, related_name='travel_buddy', to='buddies.User')),
            ],
        ),
    ]
